// probably a misnomer :P

var initrd = {
	"cd": "if (args.length < 2) {\n	args = ['cd', syscalls.getEnv('HOME')];\n}\nsyscalls.chdir(args[1]);\nsyscalls.exit(0);\n",
	"largecake": "          *                                             *\n                                               *\n                    *\n                                  *\n                                                            *\n         *\n                                                  *\n             *\n                           *             *\n                                                     *\n      *                                                               *\n               *\n                               (             )\n                       )      (*)           (*)      (\n              *       (*)      |             |      (*)\n                       |      |~|           |~|      |          *\n                      |~|     | |           | |     |~|\n                      | |     | |           | |     | |\n                     ,| |a@@@@| |@@@@@@@@@@@| |@@@@a| |.\n                .,a@@@| |@@@@@| |@@@@@@@@@@@| |@@@@@| |@@@@a,.\n              ,a@@@@@@| |@@@@@@@@@@@@.@@@@@@@@@@@@@@| |@@@@@@@a,\n             a@@@@@@@@@@@@@@@@@@@@@' . `@@@@@@@@@@@@@@@@@@@@@@@@a\n             ;`@@@@@@@@@@@@@@@@@@'   .   `@@@@@@@@@@@@@@@@@@@@@';\n             ;@@@`@@@@@@@@@@@@@'     .     `@@@@@@@@@@@@@@@@'@@@;\n             ;@@@;,.aaaaaaaaaa       .       aaaaa,,aaaaaaa,;@@@;\n             ;;@;;;;@@@@@@@@;@      @.@      ;@@@;;;@@@@@@;;;;@@;\n             ;;;;;;;@@@@;@@;;@    @@ . @@    ;;@;;;;@@;@@@;;;;;;;\n             ;;;;;;;;@@;;;;;;;  @@   .   @@  ;;;;;;;;;;;@@;;;;@;;\n             ;;;;;;;;;;;;;;;;;@@     .     @@;;;;;;;;;;;;;;;;@@@;\n         ,%%%;;;;;;;;@;;;;;;;;       .       ;;;;;;;;;;;;;;;;@@;;%%%,\n      .%%%%%%;;;;;;;@@;;;;;;;;     ,%%%,     ;;;;;;;;;;;;;;;;;;;;%%%%%%,\n     .%%%%%%%;;;;;;;@@;;;;;;;;   ,%%%%%%%,   ;;;;;;;;;;;;;;;;;;;;%%%%%%%,\n     %%%%%%%%`;;;;;;;;;;;;;;;;  %%%%%%%%%%%  ;;;;;;;;;;;;;;;;;;;'%%%%%%%%\n     %%%%%%%%%%%%`;;;;;;;;;;;;,%%%%%%%%%%%%%,;;;;;;;;;;;;;;;'%%%%%%%%%%%%\n     `%%%%%%%%%%%%%%%%%,,,,,,,%%%%%%%%%%%%%%%,,,,,,,%%%%%%%%%%%%%%%%%%%%'\n       `%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'\n           `%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%'\n                  \"\"\"\"\"\"\"\"\"\"\"\"\"\"`,,,,,,,,,'\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\n                                 `%%%%%%%'\n                                  `%%%%%'\n                                    %%%     (ascii art credit http://www.chris.com/ascii/index.php?art=events/birthday)\n                                   %%%%%\n                                .,%%%%%%%,.\n                           ,%%%%%%%%%%%%%%%%%%%,\n",
	"id": "syscalls.write(syscalls.getEnv('USERNAME'));\nsyscalls.exit(0);\n",
	"ls": "var args = arguments.slice(1);\nvar allfiles = false;\nvar longlisting = false;\nwhile (args.length > 0 && args[0][0] == '-') {\n	flags = args[0];\n	args = args.slice(1);\n	for (var i = 1; i < flags.length; i++) {\n		switch (flags[i]) {\n			case 'a':\n				allfiles = true;\n				break;\n			case 'l':\n				longlisting = true;\n				break;\n			default:\n				syscalls.write('Bad option flag: \"' + flags[i] + '\"\\n');\n				return syscalls.exit(1);\n		}\n	}\n}\nif (args.length == 0) {\n	args = ['.']\n}\nfor (var i = 0; i < args.length; i++) {\n	var filelist = syscalls.listdir(args[i]);\n	if (!filelist) break;\n	for (var j = 0; j < filelist.length; j++) {\n		if (allfiles || filelist[j][0] != '.') {\n			syscalls.write(filelist[j] + '\\n');\n		}\n	}\n}\nsyscalls.exit(0);\n",
	"birthday": "var mem = [];\nfunction strwrite(dest, string) {\n	var i;\n	for (i = 0; i < string.length; i++) {\n		mem[dest + i] = string.charCodeAt(i);\n	}\n	mem[dest + i] = 0;\n}\nfunction strread(src) {\n	var out = '';\n	while (mem[src]) {\n		out += String.fromCharCode(mem[src]);\n		src++;\n	}\n	return out;\n}\nstrwrite(42, 'Andrew');\nsyscalls.write('Happy birthday!\\nEnter your name: ');\nsyscalls.read(function (line) {\n	if (line.length > 32) {\n		line = line.substr(0,32);\n	}\n	line = line.slice(0,-1);\n	strwrite(0, line);\n	syscalls.write('Enter your age: ');\n	syscalls.read(function (line) {\n		strwrite(32, line.slice(0,-1));\n		syscalls.write('On a scale of 1-10, how awesome would you like your birthday to be? ');\n		syscalls.read(function (line) {\n			try {\n				line = parseInt(line);\n			} catch (e) {\n				syscalls.write(\"That's not a number! You don't deserve a birthday!\\n\");\n				syscalls.exit(1);\n			}\n			if (line < 1 || line > 10) {\n				syscalls.write(\"That's not between 1 and 10! You don't deserve a birthday!\\n\");\n				syscalls.exit(1);\n			}\n			switch (line) {\n				case 1:\n					syscalls.write(\"happy birthday\\n\");\n					break;\n				case 2:\n				case 3:\n					syscalls.write(\"Happy birthday!\\n\");\n					break;\n				case 4:\n				case 5:\n				case 6:\n					syscalls.write(\"Happy birthday, \" + strread(0) + '!\\n');\n					break;\n				case 7:\n					syscalls.write(\"Happy \" + strread(32) + \"th birthday, \" + strread(0) + '!\\n');\n					break;\n				case 8:\n					syscalls.write(\"Happy \" + strread(32) + \"th birthday, \" + strread(0) + '!\\nI hope you have an awesome day and live forever!\\n');\n					break;\n				case 9:\n					syscalls.write(syscalls.readfile('/etc/cake1') + \"\\nHappy \" + strread(32) + \"th birthday, \" + strread(0) + '!\\nI hope you have an awesome day and live forever!\\n');\n					break;\n				case 10:\n					if (strread(0) == strread(42)) {\n						syscalls.write(syscalls.readfile('/etc/cake2') + \"\\n\\nHAPPY BIRTHDAY \" +  strread(0).toUpperCase() + '!!!!!\\n\\nYou are the most amazing person ever and I am soooooooo happy you\\'ve lived this long!\\nNEVER STOP BEING AWESOME!\\n\\n');\n					} else {\n						syscalls.write('Only ' + strread(42) + ' can have the awesomest birthday!\\n');\n					}\n					break;\n			}\n			syscalls.exit(0);\n		});\n	});\n});\n",
	"echo": "syscalls.write(arguments.slice(1).join(' '));\nsyscalls.exit(0);\n",
	"write": "if (arguments.length < 2) {\n	syscalls.write('Usage: write [file]\\n');\n	return syscalls.exit(1);\n}\nvar filepath = arguments[1];\nif (!syscalls.checkPerms(filepath, 1)) {\n	syscalls.write('Access denied\\n')\n	return syscalls.exit(2);\n}\nsyscalls.write('Mark the end of your file with a line containing only !EOF!\\n');\nvar filebuf = '';\nvar readloop = function (line) {\n	if (line == '!EOF!\\n') {\n		syscalls.exit(syscalls.writeFile(filepath, filebuf));\n	} else {\n		filebuf += line;\n		syscalls.read(readloop);\n	}\n}\nsyscalls.read(readloop);\n",
	"hint4": "The correct field to hack is the \"Age\" input. Try entering the following age for a 10-awesome birthday:\nAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\n",
	"pwd": "syscalls.write(syscalls.getEnv('PWD'));\nsyscalls.exit(0);\n",
	"cat": "for (var i = 1; i < arguments.length; i++) {\n	var s = syscalls.readfile(arguments[i]);\n	if (typeof s == 'string') {\n		syscalls.write(s);\n	}\n}\nsyscalls.exit(0);\n",
	"hint1": "Good job!\n\nYou used the \"cat\" command to read this hint. You can use the \"birthday\" command to have a birthday!\n",
	"hint2": "You want to have the most awesomest birthday possible, right? Why can't you do that?\n",
	"smallcake": "           iiiiiiiiii\n          |:H:a:p:p:y:|\n        __|___________|__\n       |^^^^^^^^^^^^^^^^^|\n       |:B:i:r:t:h:d:a:y:|\n       |                 |\n       ~~~~~~~~~~~~~~~~~~~\n",
	"hint5": "Try the following age:\nabcdefghijklmnopqrstuvwxyz\n",
	"hint6": "You should be able to solve it by this point!\n\nIf you can't...\n\n1)  :(\n2)  The next hint has the correct answer.\n",
	"hint7": "1) Load the page\n2) When I say to type something, type it without the quotes and then press enter.\n3) Type in \"birthday\"\n4) Type in \"Cole\"\n5) Type in \"AAAAAAAAAACole\" (that's 10 As)\n6) Type in \"10\"\n7) Happy birthday!\n",
	"true": "syscalls.exit(true);\n",
	"etcpasswd": "{\n 0: {\"name\": \"root\", \"group\": \"root\", \"home\": \"/\", \"shell\": \"/bin/bash\"}\n 1: {\"name\": \"birthdayboy\", \"group\": \"birthdayboy\", \"home\": \"/home/birthdayboy\", \"shell\": \"/bin/bash\"}\n}\n",
	"bash": "function parse(line) {\n	line = line.substr(0,line.length-1);\n	args = line.split(' ');\n	switch (args[0]) {\n		case '':\n			cycle();\n			break;\n		case 'exit':\n			return syscalls.exit(0);\n		case 'cd':\n			if (!args[1]) {\n				args[1] = syscalls.getEnv('HOME');\n			}\n			syscalls.chdir(args[1]);\n			cycle();\n			break;\n		default:\n			syscalls.exec(args[0], args, syscalls.getEnv(), cycle);\n	}\n}\nfunction cycle() {\n	if (syscalls.getLWC() != '\\n') {\n		syscalls.write('\\n');\n	}\n	syscalls.write(syscalls.getEnv('USERNAME') + '@' + syscalls.getEnv('HOSTNAME') + ' [' + syscalls.getEnv('PWD') + '/] $ ');\n	syscalls.read(parse);\n}\ncycle();\n",
	"hint3": "So, Andrew has monopolized the birthday awesomeness, eh?\nThere's gotta be some way to get it back from him!\n\nThe first way to start hacking stuff is to enter lots of random stuff the program isn't expecting.\nTry doing that for all your different opportunities to enter stuff!\n"
};
